webtalk_init -webtalk_dir D:/PHD/2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_testing/2020_CiM_testing.sim/sim_testcase6_ts_mav/behav/xsim/xsim.dir/testcase6_ts_mav_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug  6 00:14:36 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211775784_0_0_360" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fad9e2e5-f5a4-40b9-8bba-dd2a0213eb8b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "04c103d3400b4441a51abdb081bf4304" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 253985694 -regid "211775784_0_0_360" -xml D:/PHD/2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_testing/2020_CiM_testing.sim/sim_testcase6_ts_mav/behav/xsim/xsim.dir/testcase6_ts_mav_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/PHD/2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_testing/2020_CiM_testing.sim/sim_testcase6_ts_mav/behav/xsim/xsim.dir/testcase6_ts_mav_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/PHD/2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_testing/2020_CiM_testing.sim/sim_testcase6_ts_mav/behav/xsim/xsim.dir/testcase6_ts_mav_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
