webtalk_init -webtalk_dir D:/PHD/2019_CiM/Testing/FPGA/testcase1_scanchain_singleReadWrite/testcase1_scanchain_singleReadWrite.sim/sim_testcase1/behav/xsim/xsim.dir/testcase1_scanchain_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 10 09:21:24 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211775784_0_0_360" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fad9e2e5-f5a4-40b9-8bba-dd2a0213eb8b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "33cedce99fa945c2828ed89e18747f92" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "148" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "8" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "550 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "32 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "258" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "10" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.77_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "124484_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1043262988 -regid "211775784_0_0_360" -xml D:/PHD/2019_CiM/Testing/FPGA/testcase1_scanchain_singleReadWrite/testcase1_scanchain_singleReadWrite.sim/sim_testcase1/behav/xsim/xsim.dir/testcase1_scanchain_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/PHD/2019_CiM/Testing/FPGA/testcase1_scanchain_singleReadWrite/testcase1_scanchain_singleReadWrite.sim/sim_testcase1/behav/xsim/xsim.dir/testcase1_scanchain_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/PHD/2019_CiM/Testing/FPGA/testcase1_scanchain_singleReadWrite/testcase1_scanchain_singleReadWrite.sim/sim_testcase1/behav/xsim/xsim.dir/testcase1_scanchain_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
