# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tc6_ts_mav.xdc

# IP: ip/clk_core/clk_core.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_core || ORIG_REF_NAME==clk_core} -quiet] -quiet

# XDC: ip/clk_core/clk_core_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_core || ORIG_REF_NAME==clk_core} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_core/clk_core.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_core || ORIG_REF_NAME==clk_core} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_core/clk_core_ooc.xdc
