webtalk_init -webtalk_dir C:/Users/ECE-IT-Admin/Box/Shanshan_Xie/Research_work/1_2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_test_ver2/2020_CiM_test_ver2.sim/sim_testcase7_start_DAC/behav/xsim/xsim.dir/testcase5_top_DACandMAV_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug 13 15:24:16 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ea5d9c86-90ef-4de7-bb3b-193215d7e98f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bda37e90d3fb405ca1483dd087c78c64" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "965746500436 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.64_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7088_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3156284819 -regid "" -xml C:/Users/ECE-IT-Admin/Box/Shanshan_Xie/Research_work/1_2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_test_ver2/2020_CiM_test_ver2.sim/sim_testcase7_start_DAC/behav/xsim/xsim.dir/testcase5_top_DACandMAV_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ECE-IT-Admin/Box/Shanshan_Xie/Research_work/1_2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_test_ver2/2020_CiM_test_ver2.sim/sim_testcase7_start_DAC/behav/xsim/xsim.dir/testcase5_top_DACandMAV_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ECE-IT-Admin/Box/Shanshan_Xie/Research_work/1_2019_CiM/Testing/Cifar10_FPGA_Measurement/2020_CiM_test_ver2/2020_CiM_test_ver2.sim/sim_testcase7_start_DAC/behav/xsim/xsim.dir/testcase5_top_DACandMAV_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
